###
### This docker-compose.yml is only for local test purpose.
###

version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    environment:
      - DOCKER=TRUE
      - MODE=DEV
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app
    ports:
      - ${PORT_DEV}:${PORT_DEV}

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    volumes:
      - ./data/sql/mysql:/var/lib/mysql
      - ./data/sql/init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    restart: always
    ports:
      - "3333:3306"
