###
### This docker-compose.yml is only for local test purpose.
###

version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    environment:
      - DOCKER=TRUE
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT_DEV}:${PORT_DEV}

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/sql/mysql:/var/lib/mysql
    restart: always
    ports:
      - "3333:3306"
