/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Segment } from './Segment';
/**
 * Grade element stored in db and consumed by client. The values are between 0~100.
 */
export type GradeElement = {
    /**
     * '課號', e.g. CSIE1212
     */
    course_id1: string;
    /**
     * Semester between 90-1 ~ 130-2
     */
    semester: string;
    /**
     * The lecturer.
     */
    lecturer: (string | null);
    /**
     * '班次'
     */
    class_id: (string | null);
    /**
     * A list of segments. The segments are expected to be disjoint, and taking up the whole [0, 9] range. The sum is expected to be (nearly) 100.
     */
    segments: Array<Segment>;
    /**
     * A string generated by backend server.
     */
    id?: string;
};

