name: Validate .env

on:
  push:
    branches: master

jobs:
  validate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-env
        with:
          env-base64: ${{ secrets.ENV_FILE_BASE64 }}
      - id: env-sha256-secret
        run: |
          echo "sha256=$(sha256sum -b .env | cut -d ' ' -f 1)" > $GITHUB_OUTPUT
          echo "sha256=$(sha256sum -b .env | cut -d ' ' -f 1)"
      - id: env-sha256-file
        run: |
          echo "sha256=$(cat .env.sha256)" > $GITHUB_OUTPUT
          echo "sha256=$(cat .env.sha256)"
      - if: ${{ steps.env-sha256-file.outputs.sha256 != steps.env-sha256-secret.outputs.sha256 }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Your .env.sha256 is out-dated.')
