name: Validate .env

on:
  push:
    branches: master

jobs:
  validate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-env
        with:
          env-base64: ${{ secrets.ENV_FILE_BASE64 }}
      - id: env-sha256-secret
        run: echo "sha256=$(sha256sum -b .env)" > $GITHUB_OUTPUT
      - id: env-sha256-file
        run: echo "sha256=$(cat .env.sha256sum)" > $GITHUB_OUTPUT
      - if: ${{ steps.env-sha256-file != steps.env-sha256-secret }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Your .env.sha256 is out-dated.')
