name: Validate Extension PR

on:
  pull_request:
    branches:
      - extension

jobs:
  get-and-validate-version:
    # We ignore the case of initial commit or no manifest.json in this job :P

    env:
      MANIFEST: "./manifest.json"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        # fetch-depth: 2
        # ref: "extension"

      - id: next-version
        uses: ./.github/actions/get-extension-version
        with:
          manifest: ${{ env.MANIFEST }}

      # ! This may crash if action is modified? 🙃
      - uses: actions/checkout@v4
        with:
          ref: "extension"
      - id: prev-version
        uses: ./.github/actions/get-extension-version
        with:
          manifest: ${{ env.MANIFEST }}

      - name: Get prev version date
        id: get-prev-date
        run: echo "data=$(git log -1 --format=%cd --date=format:%Y/%m/%d)" > $GITHUB_OUTPUT

      - if: ${{ steps.next-version.outputs.version == steps.prev-version.outputs.version }}
        uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.next-version.outputs.version }}
        with:
          script: |
            core.setFailed('Version ${{ env.VERSION }} already published on ${{ steps.get-prev-date.outputs.date }}.')

    outputs:
      version: ${{ steps.next-version.outputs.version }}
